---
name: SlapperPlayerCount
version: 2.1.3
main: ethaniccc\SlapperPlayerCount\Main
description: Get the amount of players on a world or server using SimpleNPC!
api: 3.12.0

depend:
  - SimpleNPC
...
